### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by toastyfen** [flathub/net.brinkervii.grapejuice#108]
Flatpak is currently on 7.11.4, stable is 7.14.4
Latest version is a major improvement, bringing the ability to switch the release channel allowing for the game to be played again (zintegration branch)

**Comment by TheNexusAvenger** [comment]
The version of WINE bundled in the Flatpak needs to be updated as well. A version of 7.20 is used when Roblox *requires* 8.0 or newer. I've been trying to get this working without a pre-compiled version, but I am not having much luck.
