### ISSUE TITLE
Error loading v7.20.11

### ISSUE THREAD

**Issue by WolfOfTheStars** [flathub/net.brinkervii.grapejuice#124]
So I had only just recently gotten Grapejuice to load Roblox just before the recent update went through and now I am struggling to load Roblox once again. The App fails to start up and will tell me to create a recovery dump only to fail doing so leaving me with zero error codes or messages to add to this report. Player, won't even start up and fails with Wine to top all this off. I'm not sure what to do and if there is a way to fix this, please let me know! I've uninstalled and reinstalled it at least 6 times getting the exact same results.

**Comment by guihkx** [comment]
I was having the same issue, unfortunately.

I solved it by manually updating the Wine prefix created by Grapejuice - though this was supposed to be done automatically. :(

Try running the following command on a terminal window to update all your Grapejuice prefix(es) (when asked to install Mono, just cancel it):

```bash
find ~/.var/app/net.brinkervii.grapejuice/data/grapejuice/prefixes -mindepth 1 -maxdepth 1 -type d | xargs -I '{}' flatpak run '--env=WINEPREFIX={}' --command=wineboot net.brinkervii.grapejuice -u
```

**Comment by WolfOfTheStars** [comment]
Thank you for replying, this helps me massively, though would it be possible to write the commands in a more easier to understand way? I'm still very new to Linux and I don't fully understand how to input the commands right away. I'm also on Arch Garuda if that helps in any way.

**Comment by WolfOfTheStars** [comment]
Hey, so I tried doing what you suggested, is there a better way to explain the code outside of the thing you set up? I have no idea how to properly input it and it won't load the command otherwise.

**Comment by guihkx** [comment]
Just copy everything from my previous post, paste it into a Terminal window (search for 'terminal' in your apps list), and hit <kbd>Enter</kbd>.

You probably want to 'kill' any running instance of Grapejuice before doing that, though. So first run this command:

```bash
flatpak kill net.brinkervii.grapejuice 
```

And then this one:

```bash
find ~/.var/app/net.brinkervii.grapejuice/data/grapejuice/prefixes -mindepth 1 -maxdepth 1 -type d | xargs -I '{}' flatpak run '--env=WINEPREFIX={}' --command=wineboot net.brinkervii.grapejuice -u
```

And after that you can try playing Roblox again.

**Comment by WolfOfTheStars** [comment]
I tried running the kill command and it tells me that it's not running? but whenever I put in the commands it's not running it.

**Comment by WolfOfTheStars** [comment]
Would it help to mention Im running off of the Arch Garuda Linux? I use Sudo commands.

**Comment by guihkx** [comment]
>I tried running the kill command and it tells me that it's not running?

That's alright, the command was only supposed to 'kill' Grapejuice if it was running. You can proceed.

>Would it help to mention Im running off of the Arch Garuda Linux?

That's fine, your distro should not matter.

>I use Sudo commands.

Don't do that. Copy and paste the command exactly as you see it.

**Comment by WolfOfTheStars** [comment]
Including the do and done? Because on mine it's showing it in red and it's not running it.

This is all that it's doing: 

![Screenshot_20230907_175722-1](https://github.com/flathub/net.brinkervii.grapejuice/assets/144286530/224f775a-c62d-4c35-9cd8-95ef16ab4e81)

**Comment by guihkx** [comment]
Ah, I think I see what the problem is.

For whatever reason, your default shell is not Bash. No worries though, just type `bash`, hit <kbd>Enter</kbd> and then try running that command again.

**Comment by WolfOfTheStars** [comment]
Oh ok, so I just do it at the end of the original command and it should work? Or would it be in the beginning? Sorry, I'm very new to linux and still learning all of this.

**Comment by guihkx** [comment]
>so I just do it at the end of the original command and it should work?

No, you will delete everything you wrote, type *just* `bash`, and then hit <kbd>Enter</kbd>.

And only then you can run that big command again.

>Sorry, I'm very new to linux and still learning all of this.

It's okay. :)

**Comment by WolfOfTheStars** [comment]
Ahh okay!! Thank you! The clarification helps loads lol I'll let you know if it's successful!

**Comment by WolfOfTheStars** [comment]
We've got success!! Thank you so much again Guihkx for the help!!

**Comment by guihkx** [comment]
Glad it worked! ^^

Still, I'd consider this to be a bug (though I'm not exactly sure where), so thanks for confirming that my workaround fixes things.

FWIW I've updated the command to a more 'universal' one, which should work regardless of people's setups.
