### ISSUE TITLE
Roblox Wont Load

### ISSUE THREAD

**Issue by Sologolos** [flathub/net.brinkervii.grapejuice#137]
![Screenshot 2023-10-05 20-49-46](https://github.com/flathub/net.brinkervii.grapejuice/assets/143910612/d4511d53-4a0e-4227-ae03-7268d042ad06)
It keep just saying this, ill try my best to find a fix, but what should i do?

**Comment by lunarlattice0** [comment]
Roblox pushed a bad update, this may take a while to resolve...

**Comment by Sologolos** [comment]
How long, if you know, like weeks? months?
