### ISSUE TITLE
constant crashing on steam deck

### ISSUE THREAD

**Issue by Epic62790** [flathub/net.brinkervii.grapejuice#149]
i cannot fix on the flatpak ver of this fix plz

**Comment by Epic62790** [comment]
whenever i play a game it crashes after a minute or minutes of playing

**Comment by Ruffus16** [comment]
This is happening to me too.

**Comment by VitulakCZ** [comment]
It's because of a new feature. Look at the "Roblox Status" paragraph.
https://gitlab.com/brinkervii/grapejuice
