### ISSUE TITLE
Verification in flathub

### ISSUE THREAD

**Issue by NamelessGO** [flathub/net.brinkervii.grapejuice#161]
Hello, been trying to increase the number of projects being validated on flathub to increase trust in the apps and increase flathub adoption

Saw this post which said that flatpack was [maintained by a third party](https://gitlab.com/brinkervii/grapejuice/-/issues/434#note_1310309123), is this still the case?

The [docs](https://brinkervii.gitlab.io/grapejuice/install-on/flatpak/) treats it as an official method to install

> A verified app is an app that is published on Flathub by its original developer or a third party approved by the developer. Flathub has verified the developer's identity using the app id and the developer's website or profile on a source code hosting site.

Verification docs: https://docs.flathub.org/docs/for-app-authors/verification

**Comment by TheComputerGuy96** [comment]
@NameLessGO The Flatpak version isn't maintained by the app's creator/maintainer (BrinkerVII)

Initially she was pretty against a Flatpak version (but I guess she's fine with it now)

Unfortunately the maintainer has been inactive and there have been some breaking changes relating to the application this wrapper is trying to run (so I will have to use a forked repo or apply various patches to keep this Flatpak working good enough)
