### ISSUE TITLE
[PLEASE READ THIS] The state/future of the project

### ISSUE THREAD

**Issue by TheComputerGuy96** [flathub/net.brinkervii.grapejuice#180]
As you can see this Flatpak hasn't been updated for a while and it has recently been suffering from major issues

This is because the upstream project (Grapejuice) hasn't been updated for a few months and lacks important fixes for the new updates (and shows no sign of updating)

I've recently been thinking of ways to fix this issue and here's at least 2 of them:

1. Create and apply the most important fixes directly to the Flatpak to keep it alive (non-Flatpak users won't benefit from this and the program will still be in a meh state though)
2. Go all in and start hard-forking the project and archive this one (this will require submitting an application request to Flathub though so this is a slow process)

For now applying hotfixes is probably the best option to prevent issue flooding 🐸

**Comment by sewnie** [comment]
Vinegar stays winning
