### ISSUE TITLE
Question about the GPL 3 license

### ISSUE THREAD

**Issue by guihkx** [flathub/net.brinkervii.grapejuice#19]
Hi!

I'm attempting to do some general cleanup in this repo by removing patches and whatnot (I haven't made the changes public yet), and the GPL3 license file caught my attention.

Are there any actual files in this repo licensed under it?

Since most Flathub repos don't provide any license, would you oppose to the idea of removing it from here too?

Thanks!

**Comment by lunarlattice0** [comment]
Grapejuice itself is licensed under GPL3. Since this is a derivative work, I have to license it under the same GPL3.

**Comment by guihkx** [comment]
I'm unsure if files used for packaging a software would count as derivative work, but I suppose having the license doesn't do any harm anyway.

Thanks for the clarification!
