### ISSUE TITLE
Signin broken in roblox studio

### ISSUE THREAD

**Issue by marcjuhl** [flathub/net.brinkervii.grapejuice#26]
It freezes when I try to log in via browser and says try again when I try to login in to the app 
[Image](https://imgur.com/TD8Cxsr)

**Comment by lunarlattice0** [comment]
Known issue, studio login has been extremely buggy. It works for some and not for others. Currently, the best way to login is to click log-in via browser, but even then studio has trouble. 

You can also try resetting the prefix. I've found that it works for some. 

If you still have trouble signing in, please come to the Discord where we will be happy to help.
