### ISSUE TITLE
Server calling issues

### ISSUE THREAD

**Issue by OliyTheWolf** [flathub/net.brinkervii.grapejuice#32]
I needed to reinstall flatpak recently and empty out my data. when I attempt to reinstall Grapejuice it isn't able to call a item from the server. I don't know if it is just me or if other people are having the same issue. (I'm new to Linix and still learning the ropes)

Device:
Steam Deck 64 gb model

(1)(deck@steamdeck ~)$ flatpak install flathub net.brinkervii.grapejuice
Looking for matches…
Remote ‘flathub’ found in multiple installations:

   1) system
   2) system (SDCARD)

Which do you want to use (0 to abort)? [0-2]: 2

net.brinkervii.grapejuice permissions:
    ipc    network    pulseaudio    wayland    x11    devices    devel    multiarch

        ID                                  Branch          Op          Remote           Download
 1. [✗] net.brinkervii.grapejuice           stable          i           flathub          14.3 MB / 137.2 MB

Error: While pulling app/net.brinkervii.grapejuice/x86_64/stable from remote flathub: Server returned status 404: Not Found
error: Failed to install net.brinkervii.grapejuice: While pulling app/net.brinkervii.grapejuice/x86_64/stable from remote flathub: Server returned status 404: Not Found

**Comment by lunarlattice0** [comment]
flathub is having trouble at the moment, please use
`flatpak install net.brinkervii.grapejuice --no-static-deltas`
or wait until the problem gets fixed by flathub.

**Comment by lunarlattice0** [comment]
Solved by flathub as of today.
