### ISSUE TITLE
i can't play games

### ISSUE THREAD

**Issue by ghost** [flathub/net.brinkervii.grapejuice#62]
![srtshdgd](https://user-images.githubusercontent.com/94055989/235445988-a6d1d89c-c0c7-484a-a2b2-a9a68a428e4d.png)

beforce i update grapejuice it was happening sometimes when i'm trying to play "Arcane Odyssey [Early Access]", but after update it's happening to all games. I using steam deck

**Comment by lunarlattice0** [comment]
Please restart your device, and try reinstalling with `flatpak remove net.brinkervii.grapejuice --delete-data`

**Comment by ghost** [comment]
Error: Error uninstalling: Directory not empty
error: Failed to uninstall net.brinkervii.grapejuice: Error uninstalling: Directory not empty

this is that popout

**Comment by lunarlattice0** [comment]
`flatpak repair`

then `flatpak remove net.brinkervii.grapejuice --delete-data`

then `flatpak install net.brinkervii.grapejuice`

**Comment by ghost** [comment]
(deck@PsP ~)$ flatpak repair
Working on the system installation at /var/lib/flatpak
Privileges are required to make changes; assumi[4/50] Verifying flathub:runtime/org.freedeskto[6/50] Verifying flathub:app/org.kde.krita/x86_[8/50] Verifying flathub:runtime/org.freedeskto[9/50] Verifying flathub:runtime/org.gtk.Gtk3theme.Breeze/x86_64/3.22…
Skipping non-deployed ref flathub:app/net.brink[14/50] Verifying flathub:runtime/org.kde.Platf[16/50] Verifying flathub:runtime/org.kde.Platf[18/50] Verifying flathub:app/org.polymc.PolyMC[19/[50/50] Verifying flathub:runtime/org.freedesktop.Platform/x86_64/22.08…
Checking remotes...
(deck@PsP ~)$ flatpak remove net.brinkervii.grapejuice --delete-data
error: net.brinkervii.grapejuice/*unspecified*/*unspecified* not installed
(1)(deck@PsP ~)$ flatpak install net.brinkervii.grapejuice
Looking for matches…

net.brinkervii.grapejuice permissions:
    ipc            network     pulseaudio     x11     devices     devel
    multiarch



        ID                              Branch       Op      Remote       Download
 1. [✓] net.brinkervii.grapejuice       stable       i       flathub      1.0 kB / 138.1 MB

Installation complete.


.
.
.

It's installed now? I don't see anything new installed after this

**Comment by lunarlattice0** [comment]
Yes

**Comment by lunarlattice0** [comment]
Closed due to lack of information, and the fact that WINE is dead.
