### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by ameliastratfor** [flathub/net.brinkervii.grapejuice#69]
it now comes up with a pop-up saying "wine is not supported" which means it is unable to launch the game, please fix because this is the only steam deck method of launching roblox

**Comment by guihkx** [comment]
Please read:

- https://www.gamingonlinux.com/2023/04/roblox-intentionally-blocking-linux-with-wine-in-their-new-update/
- https://devforum.roblox.com/t/the-new-roblox-64-bit-byfron-client-forbids-wine-users-from-using-it-most-likely-unintentional/2305528

**Comment by lunarlattice0** [comment]
IT'S OVER :(
